.PHONY: build test clean install

build:
	@echo "Building application..."
	bundle install
	
test:
	@echo "Running tests..."
	rake test

clean:
	@echo "Cleaning..."
	rm -rf tmp/
	
install:
	bundle install

